// Writes tools-feral3/ASSET-REPORT.md: the before/after table of the asset optimisation (run audit.js and optimize.js stage2 first).
const fs=require('fs'),path=require('path');
const a=JSON.parse(fs.readFileSync(path.join(__dirname,'audit.json'),'utf8')),o=JSON.parse(fs.readFileSync(path.join(__dirname,'optimized.json'),'utf8')),man=JSON.parse(fs.readFileSync(path.join(__dirname,'..','public','feral3','models','manifest.json'),'utf8'));
const names={small1:'Small 1',small2:'Small 2',small3:'Small 3',medium1:'Medium 1',medium2:'Medium 2',medium3:'Medium 3',large1:'Large 1',large2:'Large 2',boss:'Final Boss',male:'Male Character',female:'Female Character',pistol:'Pistol',shotgun:'Shotgun',rifle:'Rifle',bolt:'Bolt Action Rifle',mg:'Machine Gun'};
let md='# Feral 3.0 - asset audit and optimisation report\n\nAll 34 files in the asset folder were inspected (read-only). Every model is a single static mesh with PBR textures (base colour, normal, metal/roughness), **no rig and no animations**, in arbitrary units, with the creatures long along Z and the guns long along X. The two Map Sections are layout blueprints only and are not used (not committed).\n\n| asset | file before | tris before | textures before | file after | tris after (LOD0 / LOD1 / LOD2) | textures after | real size (m) |\n|---|---|---|---|---|---|---|---|\n';
let tb=0,ta=0;
for(const id of Object.keys(names)){ const b=a.find(x=>x.file===names[id]+'.glb'), r=man[id]; const t=b.textures.map(x=>x.split(' ')[0]).filter((v,i,s)=>s.indexOf(v)===i).join(', '); const tex=id.startsWith('small')?'1024 WebP':'2048 WebP'; tb+=b.sizeMB; ta+=r.bytes/1048576; md+='| '+names[id]+' | '+b.sizeMB+' MB | '+Math.round(b.tris).toLocaleString('en-US')+' | '+t+' JPEG x3 | '+(r.bytes/1048576).toFixed(2)+' MB | '+(r.lods.length>1?r.lods.map(x=>x.toLocaleString('en-US')).join(' / '):r.lods[0].toLocaleString('en-US'))+' | '+tex+' x3 | '+r.size.map(x=>x.toFixed(2)).join(' x ')+' |\n'; }
const maps=a.filter(x=>x.file.startsWith('Map'));
md+='| Map Section 1 / 2 | '+maps.map(m=>m.sizeMB+' MB').join(' / ')+' | '+maps.map(m=>Math.round(m.tris).toLocaleString('en-US')).join(' / ')+' | 4096 JPEG | not used (blueprints) | - | - | - |\n';
md+='\n**Totals (16 models):** '+tb.toFixed(0)+' MB before -> '+ta.toFixed(1)+' MB after ('+(100-ta/tb*100).toFixed(1)+'% smaller). With the procedural textures (~1.5 MB), sounds (synthesised in code, 0 MB) and the three.js library the whole game is about 38 MB; only 3 models (~5 MB) are needed before the menu appears, the rest stream in while you play.\n\n## What was done\n- Simplified with meshoptimizer (weld + simplify) to the triangle budgets: creatures 30-50k, boss 80k, guns 20-25k, survivors 40k. Creatures also get LOD1 (30%) and LOD2 (7%) copies that share vertices and textures; the game picks the level by distance.\n- Textures resized (creatures 1024 / 2048, everything else 2048) and converted from JPEG to WebP; geometry quantised and meshopt-compressed (EXT_meshopt_compression).\n- Orientation, scale and pivot baked into the vertices: creatures and survivors face +Z with the origin at the feet; guns have the muzzle on +Z (found by comparing the cross-section at both ends) with the origin at the centre. Sizes are in metres (survivors 1.8 m, creatures 1.75-8.5 m, guns 0.22-1.15 m).\n- Because the models have no skeleton they are animated in the vertex shader (walk cycle, tail, lunge, flinch, crouch, fall-over death with a burning dissolve), and the guns are animated procedurally (bob, sway, recoil springs, pump/bolt cycles, per-gun reloads).\n- KTX2 was not used (no toktx encoder installed): the WebP textures decode to GPU memory uncompressed, roughly 0.8 GB of video memory for the whole set (2048 textures x3 per model, with mip-maps). Fine on a desktop GPU with 4 GB or more; compressing to KTX2 (about 6x smaller on the GPU) is the first thing to do for the mobile version.\n- Not committed: the originals and the Map Sections (the .gitignore blocks the folder and `*.glb` raw copies); the biggest committed file is under 3.1 MB.\n';
fs.writeFileSync(path.join(__dirname,'ASSET-REPORT.md'),md);console.log(md.slice(0,1800));
